// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRVkcmHbZrAhaRpNbzRc13OkaHrwfkWq4',
    appId: '1:729522164639:web:4f6a07150d8a8a87e263aa',
    messagingSenderId: '729522164639',
    projectId: 'webrtctest-c54bc',
    authDomain: 'webrtctest-c54bc.firebaseapp.com',
    storageBucket: 'webrtctest-c54bc.appspot.com',
    measurementId: 'G-5C31J2K1PM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhh8p4mfyz82wNy6KDMLX0fytbkKHN0z4',
    appId: '1:729522164639:android:2f507dfaed386435e263aa',
    messagingSenderId: '729522164639',
    projectId: 'webrtctest-c54bc',
    storageBucket: 'webrtctest-c54bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw4WBV0JAHfpExDFGTmHbeHSdIPjkcajM',
    appId: '1:729522164639:ios:2c359087606fd539e263aa',
    messagingSenderId: '729522164639',
    projectId: 'webrtctest-c54bc',
    storageBucket: 'webrtctest-c54bc.appspot.com',
    iosClientId:
        '729522164639-hvprh3plh09b0228i85dr0ndbulstute.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoAgora',
  );
}
